import {Platform, StyleSheet,
 Dimensions} from 'react-native';
 export const width= Dimensions.get('window').width;
 export const height= Dimensions.get('window').height;
export const styles=StyleSheet.create({

    Textinput1:{
      borderWidth:1,borderColor:'#00a8ff',
      paddingTop:height/45,paddingBottom:height/45,paddingLeft:width/25,borderRadius:height/80,margin:height/60
    },
    Touchabl_login:{
      marginLeft:width/28,
      marginRight:width/28,padding:height/55,backgroundColor:'#518a00',borderRadius:height/80
    },
    Text_login_Touchable:{
      color:'white',textAlign:'center',fontFamily:'BYekan',fontSize:20
    },
    View_login_pictur:{
      alignItems:'center',flex:0.2
    },
    input_sabtnam:{
        borderWidth:1,borderColor:'#518a00',
        paddingTop:height/50,paddingBottom:height/50,paddingLeft:width/25,marginTop:height/50,
        borderRadius:height/80,marginRight:width/30,marginLeft:width/30,fontSize:20
      },
      Touchable_sabtnam:{
        marginLeft:width/30,marginTop:height/50,
        marginRight:height/60,paddingTop:height/50,paddingBottom:height/50
        ,paddingLeft:width/30,backgroundColor:'#518a00',borderRadius:height/80
      },
      Text_sabtnam_Touchable:{
        color:'white',textAlign:'center',fontFamily:'BYekan',fontSize:20
      },
      View_sabtnam_pictur:{
        flex:0.10,alignItems:'center',justifyContent:'center'
      },
      Touch_login_sabt:{
        marginLeft:width/35,marginTop:height/50,flex:0.5
        ,paddingLeft:width/20,justifyContent:'center'
      },
      Touch_login_bazyabi:{
        marginLeft:width/25,flex:0.5,justifyContent:'center'
      },
       input_login:{
    borderWidth:1
    ,borderColor:'#535c68',backgroundColor:'#CAD3C8',
  paddingTop:height/40,paddingBottom:height/45,paddingLeft:width/50,marginBottom:height/50
  ,borderRadius:height/80,marginLeft:width/25,marginRight:width/25,fontSize:20,fontFamily:'BYekan'
  },
 Touchable_codetayeed:{
    margin:height/60,paddingTop:height/50,paddingBottom:height/50,paddingLeft:width/20
    ,backgroundColor:'#518a00',borderRadius:height/80
  },
  Text_Kodetayeed_Touchable:{
    color:'white',textAlign:'center',fontFamily:'BYekan',fontSize:20
  },
  Text_Kodetayeed_codejadid:{
    margin:height/60,color:'black',fontFamily:'BYekan',fontSize:20
  },
  Text_Kodetayeed_text6raghamy:{
    color:'black',fontFamily:'BYekan',fontSize:20 
  },
  Text_Kodetayeed_ersall:{
    color:'black',fontFamily:'BYekan',fontSize:20
  },
  input_virayesh:{
    borderWidth:1
    ,borderColor:'#535c68',backgroundColor:'#CAD3C8',fontSize:20,fontFamily:'BYekan' ,
  paddingTop:height/45,paddingBottom:height/45,borderRadius:height/80,margin:height/60,paddingLeft:width/45
  },
  Touchabl_virayesh:{
    marginLeft:width/39,marginTop:height/80,
    marginRight:width/39,paddingTop:height/50,paddingBottom:height/50,paddingLeft:width/50,backgroundColor:'#518a00',borderRadius:height/80
  },
  Text_virayesh_Touchable:{
    color:'white',textAlign:'center',fontFamily:'BYekan',fontSize:20
  },
  input_codetayeed:{
    borderWidth:1
    ,borderColor:'#535c68',backgroundColor:'#CAD3C8',fontSize:20,fontFamily:'BYekan',
  paddingTop:height/30,paddingBottom:height/45,borderRadius:height/80,margin:height/60,paddingLeft:width/45
  },
  input_bazyabi:{
    borderWidth:1
    ,borderColor:'#535c68',backgroundColor:'#CAD3C8',fontSize:20,fontFamily:'BYekan',
  paddingTop:height/45,paddingBottom:height/45,borderRadius:height/80,marginTop:height/60,
  marginBottom:height/40,paddingLeft:width/45,marginLeft:width/50,marginRight:width/50
  },
  Touchabl_bazyabi:{
    marginLeft:width/39,
    marginRight:width/39,paddingTop:height/55,paddingBottom:height/55,paddingLeft:width/50,backgroundColor:'#518a00',borderRadius:height/80
  },
  Text_bozyabi_Touchable:{
    color:'white',textAlign:'center',fontFamily:'BYekan',fontSize:20
  },
  input_bazyabiramz2:{
    borderWidth:1,fontSize:20,fontFamily:'BYekan',
    borderColor:'#535c68',backgroundColor:'#CAD3C8',
  paddingTop:height/35,paddingBottom:height/45,borderRadius:height/80,margin:height/60,paddingLeft:width/45
  },
  Text_bazyabiramz2_Touchable:{
    color:'white',textAlign:'center',fontFamily:'BYekan',fontSize:20
  },
  })